# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-15 02:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import simplesite.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
                ('last_modification', models.DateTimeField(auto_now=True, verbose_name='Last Modification')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Main Content')),
                ('sort_order', models.IntegerField(blank=True, default=1, null=True, verbose_name='Sort Order')),
                ('is_public', models.BooleanField(default=True, verbose_name='Public')),
                ('is_header', models.BooleanField(default=False, verbose_name='Belongs to Header')),
                ('is_footer', models.BooleanField(default=False, verbose_name='Belongs to Footer')),
                ('_related_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='_related_model', to='contenttypes.ContentType', verbose_name='Related Content')),
            ],
            options={
                'ordering': ['sort_order', 'creation_date', 'slug'],
                'verbose_name': 'Page',
                'verbose_name_plural': 'Pages',
            },
        ),
        migrations.CreateModel(
            name='PageImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('caption', models.CharField(blank=True, max_length=255, null=True, verbose_name='Caption')),
                ('image', models.ImageField(max_length=255, upload_to=simplesite.models.get_page_image_path)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_set', to='simplesite.Page')),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
            },
        ),
        migrations.CreateModel(
            name='SocialNetwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
                ('url', models.URLField(max_length=255, verbose_name='URL')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
                ('sort_order', models.IntegerField(blank=True, default=1, null=True, verbose_name='Sort Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('image', models.ImageField(max_length=255, upload_to=simplesite.models.get_socialnetwork_image_path, verbose_name='Image')),
            ],
            options={
                'ordering': ['sort_order', 'creation_date'],
                'verbose_name': 'Social Network',
                'verbose_name_plural': 'Social Networks',
            },
        ),
    ]
