# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-06 23:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simplesite', '0002_auto_20160710_0506'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='is_footer',
        ),
        migrations.RemoveField(
            model_name='page',
            name='is_header',
        ),
    ]
