# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-12-21 01:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simplesite', '0003_auto_20161006_2321'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='alternative_url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Alternative URL'),
        ),
    ]
